### ISSUE TITLE
error module "pyraknet.bitstream" missing

### ISSUE THREAD

**Issue by TheMaxee** [wesleyd1124/WLUS#14]
wlus@ubuntu:~/WLUS$ python3.6 __main__.py
Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
    import game
  File "/home/wlus/WLUS/game.py", line 2, in <module>
    import game_types
  File "/home/wlus/WLUS/game_types.py", line 3, in <module>
    from pyraknet.bitstream import *
ModuleNotFoundError: No module named 'pyraknet.bitstream'

**Comment by wesleyd1124** [comment]
This issue is no longer relevant in the rewrite. The old version will not be receiving support.
