### ISSUE TITLE
Things I run into (Maybe note an issue :\)

### ISSUE THREAD

**Issue by DigitalData** [wesleyd1124/WLUS#2]
### Thing 1
```
Traceback (most recent call last):
  File "C:\Users\digit\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\digit\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Programs\Lego Universe\WLUS-master\WLUS-master\world_server.py", line 208, in handle_join_world
    if (player["Data"]["position"].X < 2 and player["Data"]["position"].Y < 2 and player["Data"]["position"].Z < 2):
AttributeError: 'str' object has no attribute 'X'
```

### Thing 2
```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\Users\digit\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\digit\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Programs\Lego Universe\WLUS-master\WLUS-master\player_service.py", line 22, in sync_thread
    self.sync_database()
  File "F:\Programs\Lego Universe\WLUS-master\WLUS-master\player_service.py", line 91, in sync_database
    character_table.update(character, "player_id = {}".format(character["player_id"]))
  File "F:\Programs\Lego Universe\WLUS-master\WLUS-master\database.py", line 76, in update
    c.execute(query_string)
sqlite3.OperationalError: no such column: position
```

### Thing 3
```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\Users\digit\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\digit\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Programs\Lego Universe\WLUS-master\WLUS-master\world_server.py", line 162, in handle_detailed_user_info
    char.set("cc", str(player["currency"]))
KeyError: 'currency'
```

**Comment by ghost** [comment]
These specific issues are resolved, World Loading is still a WIP in this version
