### ISSUE TITLE
I know world loading is an issue but here is another error I found

### ISSUE THREAD

**Issue by AnthonyH26** [wesleyd1124/WLUS#3]
Exception in thread Thread-24:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Anthony\Desktop\LuPvP-master\PyLUS-master\WLUS-master\world_server.py", line 237, in handle_join_world
    if (player["Data"]["position"].X < 2 and player["Data"]["position"].Y < 2 and player["Data"]["position"].Z < 2):
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by ghost** [comment]
Yes this was an issue in a previous version but it has been fixed, thank you
